FROM lorisleiva/laravel-docker:7.3
# FROM bitnami/laravel:8.6.3-debian-10-r0
USER root
COPY . /app
WORKDIR /app
RUN composer install
CMD php artisan migrate:fresh && \
    php artisan db:seed && \
    php artisan serve --port=$PORT
